desenvolvimento/App.Admin/Controllers/ContaController.cs
using App.Admin.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using App.Lib.Models;
using App.Lib.Entity;
using App.Lib.Service;
using App.Lib.Enumerator;
using Flurl;
using App.Admin.Enumerator;

namespace App.Admin.Controllers
{
    [OnlyHttps]
    public class ContaController : MasterController
    {
        public virtual ActionResult Index(string returnUrl = null)
        {
            if (returnUrl == null)
            {

                if (Request.UrlReferrer != null)
                {
                    returnUrl = Request.UrlReferrer.LocalPath;
                }
                else
                {
                    returnUrl = Url.Action("Index", "Home");
                }
                return RedirectToAction("Index", new { returnUrl = returnUrl });

            }

            ViewBag.ReturnUrl = returnUrl;
            if (SessionModel.Usuario != null)
            {
                return View("SemPermissao");
            }
            else
            {
                return View(new UsuarioViewModel());
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Index(UsuarioViewModel usuario, string returnUrl = null)
        {
            UsuarioService service = new UsuarioService();
            if (string.IsNullOrEmpty(usuario.login) || string.IsNullOrEmpty(usuario.senha))
            {
                ModelState.AddModelError("", "É obrigatório o preenchimento de Login e Senha");
            }
            else
            {
                RetornoModel<Usuario, enumUsuarioException> retorno = service.Logar(usuario.login, usuario.senha);
                if (retorno.Sucesso)
                {
                    SessionModel.Usuario = retorno.Retorno;
                    SalvarSessao();

                    var AuthenticationManager = HttpContext.GetOwinContext().Authentication;
                    AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
                    AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = true }, service.CriarIdentity(SessionModel.Usuario));

                    return Redirect(returnUrl);
                }
                else
                {
                    ModelState.AddModelError("", retorno.Mensagem);
                }
            }
            ViewBag.ReturnUrl = returnUrl;
            return View(usuario);
        }

        public virtual ActionResult Sair()
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public virtual ActionResult AlterarSenha(string returnUrl = null)
        {
            UsuarioService service = new UsuarioService();
            Usuario usuario = SessionModel.Usuario;

            if (returnUrl == null)
            {
                if (Request.UrlReferrer != null)
                {
                    returnUrl = Request.UrlReferrer.LocalPath;
                }
                else
                {
                    returnUrl = Url.Action("Index", "Home");
                }
            }
            ViewBag.ReturnUrl = returnUrl;

            UsuarioSenhaViewModel usuarioVM = new UsuarioSenhaViewModel();
            usuarioVM.id = usuario.ID;
            return View(usuarioVM);
        }

        [HttpPost]
        public virtual ActionResult AlterarSenha(UsuarioViewModel usuario, string returnUrl = null)
        {
            UsuarioService service = new UsuarioService();

            RetornoModel<Usuario, enumUsuarioException> retorno = service.MudarSenha(SessionModel.Usuario, usuario.senhaatual, usuario.senha);
            if(retorno.Sucesso)
            {
                returnUrl = returnUrl.SetQueryParams(new { msg = "Senha alterada com sucesso", msgtipo = enumTipoMensagem.sucesso });
                return Redirect(returnUrl);
            }
            else
            {
                ModelState.Clear();
                ModelState.AddModelError("", retorno.Mensagem);
                ViewBag.ReturnUrl = returnUrl;
                return View();
            }
        }

    }
}

desenvolvimento/App.Admin/Views/Conta/AlterarSenha.cshtml
@{
    ViewBag.Title = Session.GetModel<SessionModel>().Usuario.Nome;
}
@model UsuarioSenhaViewModel

<div class="page-header">
    <div class="row">
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-group page-header-icon"></i>&nbsp;&nbsp;@ViewBag.Title</h1>

        <div class="col-xs-12 col-sm-8">
            <div class="row">
                <hr class="visible-xs no-grid-gutter-h">
                <div class="pull-right col-xs-12 col-sm-auto"><a href="@Url.Action("Index","Usuario")" class="btn btn-labeled btn-flat" style="width: 100%;"><span class="btn-label icon fa fa-angle-left"></span>Voltar</a></div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">

        
        @using (Html.BeginForm("AlterarSenha", "Conta", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "panel form-horizontal" }))
        {      
            @Html.ValidationSummary(false, null, new { @class = "alert alert-danger" })
            
            <div class="panel-heading">
                <span class="panel-title">Alterar Senha</span>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="senhaatual" class="col-sm-2 control-label">Senha Atual *</label>
                    <div class="col-sm-10">
                        @Html.PasswordFor(m => m.senhaatual, new { validate = "required", @class = "form-control", placeholder = "Informe a Senha do Usuário" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="senha" class="col-sm-2 control-label">Nova Senha *</label>
                    <div class="col-sm-10">
                        @Html.PasswordFor(m => m.senha, new { validate = "required", @class = "form-control", placeholder = "Informe a Senha do Usuário" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="senharepeat" class="col-sm-2 control-label">Repita a Nova Senha *</label>
                    <div class="col-sm-10">
                        @Html.PasswordFor(m => m.senharepeat, new { validate = "required,equals[#senha]", @class = "form-control", placeholder = "Repita a Senha do Usuário" })
                    </div>
                </div>
 
                <div class="form-group" style="margin-bottom: 0;">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </div> 
            </div>
        }
    </div>
</div>

desenvolvimento/App.Admin/Views/Conta/Index.cshtml
@model UsuarioViewModel
@{
 Layout=null;
}
<!DOCTYPE html>
<!--[if IE 8]>         <html class="ie8"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
<!--[if gt IE 9]><!-->
<html class="gt-ie8 gt-ie9 not-ie">
 <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>next</title>
    <link rel="icon" href="@Url.Content("~/Content/images/favicon.ico")" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="sname" content="@Environment.MachineName">

    @Styles.Render("~/Content/css")
</head>

<!-- 1. $BODY ====================================================================================== -->
<body class="theme-adminflare page-signin">

    <!-- Page background -->
    <div id="page-signin-bg">
        <!-- Background overlay -->
        <div class="overlay"></div>
        <!-- Replace this with your bg image -->
        <img src="@Url.Content("~/Content/images/signin-bg.jpg")" alt="">
    </div>
    <!-- / Page background -->
    <!-- Container -->
    <div class="signin-container">

        <!-- Left side -->
        <div class="signin-info">
            <a href="#" class="logo">
                <img src="@Url.Content("~/Content/images/logo.png")" alt="Bradesco" style="margin-top: -5px;">
                <br /><br />
                admin
            </a> <!-- / .logo -->
            <div class="slogan">
                
                <br /><br />
            </div> <!-- / .slogan -->
        </div>
        <!-- / Left side -->
        <!-- Right side -->
        <div class="signin-form">
            @using (Html.BeginForm("Index", "Conta", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @id = "signin-form_id" }))
            {
                @Html.AntiForgeryToken();
                @Html.ValidationSummary(true)

                <div class="signin-text">
                    <span>Realize seu Acesso</span>
                </div> <!-- / .signin-text -->

                <div class="form-group w-icon">
                    @Html.TextBoxFor(m => m.login, new { validate = "required", @class = "form-control input-lg", placeholder = "Login de acesso" })
                    <span class="fa fa-user signin-form-icon"></span>
                </div> <!-- / Username -->

                <div class="form-group w-icon">
                    @Html.PasswordFor(m => m.senha, new { validate = "required", @class = "form-control input-lg", placeholder = "Senha de acesso" })
                    <span class="fa fa-lock signin-form-icon"></span>
                </div> <!-- / Password -->

                <div class="form-actions">
                    <input type="submit" value="ACESSAR" class="signin-btn bg-primary">
                </div> <!-- / .form-actions -->
            }
        </div>
        <!-- Right side -->
    </div>
    <!-- / Container -->
    <!--[if !IE]> -->
    @Scripts.Render("~/bundles/library.not.ie")
    <!-- <![endif]-->
    <!--[if lte IE 9]>
    @Scripts.Render("~/bundles/library.only.ie")
    <![endif]-->
    @Scripts.Render("~/bundles/scripts")

    <script type="text/javascript">
        init.push(function () {
            //
        });

        window.PixelAdmin.start(init);
    </script>
</body>

</html>